# Generated by Django 5.2.6 on 2025-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch_size',
            field=models.PositiveIntegerField(default=3, help_text='Max students per batch (e.g., 2-3)'),
        ),
        migrations.AddField(
            model_name='course',
            name='frequency',
            field=models.CharField(blank=True, help_text="e.g., '2 classes/week'", max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='learnings',
            field=models.TextField(blank=True, help_text='Comma-separated list of learning outcomes'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, help_text='Comma-separated list of requirements'),
        ),
        migrations.AddField(
            model_name='course',
            name='sample_projects',
            field=models.TextField(blank=True, help_text='Comma-separated list of sample projects'),
        ),
        migrations.AddField(
            model_name='course',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline for the course', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text="e.g., '60 min / class' or '3 months'", max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
