# Generated by Django 5.2.6 on 2025-09-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_course_batch_size_course_frequency_course_learnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sample_projects',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('url', models.URLField(blank=True, help_text='Link to view the project')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='academy.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
