# Generated by Django 5.2.6 on 2025-09-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_remove_course_sample_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('student_age', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('games', 'Games'), ('websites', 'Websites'), ('apps', 'Apps'), ('animations', 'Animations'), ('other', 'Other')], default='games', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('tools_used', models.CharField(blank=True, help_text='Comma-separated tools e.g. Scratch, Python', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_projects/')),
                ('demo_url', models.URLField(blank=True, help_text='Optional demo or video link')),
                ('approved', models.BooleanField(default=False, help_text='Only approved projects show on public site')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_projects', to='academy.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
