# Generated by Django 5.2.6 on 2025-09-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_studentproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_ceo',
            field=models.BooleanField(default=False, help_text='Mark as CEO/Founder'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mission',
            field=models.TextField(blank=True, help_text='Mission statement (for CEO only)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, help_text="Professional title (e.g., 'Founder & CEO')", max_length=200),
        ),
    ]
