# Generated by Django 5.2.6 on 2025-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_teacher_is_ceo_teacher_mission_teacher_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
