# Generated by Django 5.2.6 on 2025-09-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='course',
            name='frequency',
        ),
    ]
