# Generated by Django 5.2.6 on 2025-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_remove_course_batch_size_remove_course_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('premier', 'Premier'), ('prime', 'Prime')], max_length=50)),
                ('classes_per_week', models.IntegerField()),
                ('price_pkr', models.IntegerField()),
                ('price_usd', models.IntegerField()),
            ],
        ),
    ]
