# Generated by Django 5.2.6 on 2025-09-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('available_for_trial', models.BooleanField(default=True)),
                ('available_for_enrollment', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=20)),
                ('slot_type', models.CharField(choices=[('trial', 'Free Trial'), ('enrollment', 'Full Enrollment'), ('both', 'Both')], default='both', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('time_range', 'slot_type')},
            },
        ),
    ]
