# Generated by Django 5.2.6 on 2025-09-30 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_day_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('plan', models.CharField(choices=[('prime', 'Prime'), ('premier', 'Premier')], max_length=20)),
                ('classes_per_week', models.PositiveSmallIntegerField()),
                ('class_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('calculated_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_days', models.JSONField()),
                ('preferred_time_slot', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_contact', models.CharField(max_length=50)),
                ('parent_email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(choices=[('JazzCash', 'JazzCash'), ('NayaPay', 'NayaPay'), ('Payoneer', 'Payoneer')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='TrialFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_age', models.PositiveIntegerField()),
                ('preferred_day', models.CharField(max_length=20)),
                ('preferred_time', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=150)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.course')),
            ],
        ),
    ]
