# Generated by Django 5.2.6 on 2025-10-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_enrollmentformsubmission_trialformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentformsubmission',
            name='preferred_days',
            field=models.TextField(help_text='Comma-separated preferred days'),
        ),
    ]
