# Generated by Django 5.2.6 on 2025-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0013_alter_enrollmentformsubmission_preferred_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("parent", "Parent"), ("student", "Student")],
                        max_length=10,
                    ),
                ),
                ("feedback_message", models.TextField()),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="feedback_pictures/"
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
